name: hotel_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  #dio
  dio: ^5.8.0+1
  logger: ^2.5.0
  #
  flutter_svg: ^2.1.0
  isar: ^3.1.0+1
  get_it: ^8.0.3
  dartz: ^0.10.1
  go_router: ^14.8.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  intl: ^0.20.2
  geocoding: ^3.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  http: ^1.3.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

