// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjk5xrHEs5dZZCz6hAsLS3-dGWoDiucR8',
    appId: '1:1021278946419:web:fbd3e893289b708486d606',
    messagingSenderId: '1021278946419',
    projectId: 'iot-embedding-project',
    authDomain: 'iot-embedding-project.firebaseapp.com',
    databaseURL: 'https://iot-embedding-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-embedding-project.firebasestorage.app',
    measurementId: 'G-K8XE2KPRSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYAebU9QENgTWotJN2KuvlhZJTJLLWoaU',
    appId: '1:1021278946419:android:2d35bffc0726264186d606',
    messagingSenderId: '1021278946419',
    projectId: 'iot-embedding-project',
    databaseURL: 'https://iot-embedding-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-embedding-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEW_1aGtWE3YvI7fNlu0tzlqXrVIyGCG8',
    appId: '1:1021278946419:ios:a1e0e5e32890b24586d606',
    messagingSenderId: '1021278946419',
    projectId: 'iot-embedding-project',
    databaseURL: 'https://iot-embedding-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-embedding-project.firebasestorage.app',
    iosBundleId: 'com.gr15.hotelApp',
  );
}
